[books.going-infinite]
title = "Going Infinite"
author = "Michael Lewis"
format = "text"
genres = ["non-fiction"]
finished = 2024-01-01
media = "ebook"
via = "Libby"
grade = "B+"

[books.dad-jokes]
title = "Dad Jokes: The Good. The Bad. The Terrible."
author = ["Jimmy Niro"]
format = "text"
genres = ["non-fiction"]
finished = 2024-01-01
media = "paper"
via = "own"
grade = "B-"

[books.mae-volume-one]
title = "Mae: Volume One"
author = ["Gene Ha"]
format = "graphic"
genres = ["fantasy"]
finished = 2024-01-05
media = "paper"
via = "own"
grade = "B-"

[books.the-spare-man]
title = "The Spare Man"
author = "Mary Robinette Kowal"
format = "text"
genres = ["fantasy"]
finished = 2024-01-07
media = "ebook"
via = "Libby"
grade = "A-"

[books.hell-bay]
title = "Hell Bay"
author = "Will Thomas"
format = "text"
genres = ["mystery"]
finished = 2024-01-11
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-murder-of-roger-ackroyd]
title = "The Murder of Roger Ackroyd"
author = "Agatha Christie"
format = "text"
genres = ["mystery"]
finished = 2024-01-13
media = "ebook"
via = "Libby"
grade = "A"
