[books.anthropica]
title = "Anthropica"
author = "David Hollander"
format = "text"
genres = ["fiction"]
finished = 2023-01-01
media = "paper"
via = "own"
grade = "B"

[books.sixteen-ways-to-defend-a-walled-city]
title = "Sixteen Ways to Defend a Walled City"
author = "K. J. Parker"
format = "text"
genres = ["fantasy"]
finished = 2023-01-09
media = "paper"
via = "Boulder Public Library"
grade = "A"

[books.the-echo-maker]
title = "The Echo Maker"
author = "Richard Powers"
format = "text"
genres = ["mystery"]
finished = 2023-01-19
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-winners]
title = "The Winners"
author = "Fredrik Backman"
format = "text"
genres = ["fiction"]
finished = 2023-01-31
media = "ebook"
via = "own"
grade = "A"

[books.critical-mass]
title = "Critical Mass"
author = "Daniel Suarez"
format = "text"
genres = ["science fiction"]
finished = 2023-03-02
media = "ebook"
via = "own"
grade = "B"

[books.how-to-rule-an-empire]
title = "How to Rule an Empire and Get Away with it"
author = "K. J. Parker"
format = "text"
genres = ["fantasy"]
finished = 2023-03-07
media = "paper"
via = "Boulder Public Library"
grade = "B+"

[books.the-blade-itself]
title = "The Blade Itself"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-03-22
media = "ebook"
via = "Libby"
grade = "A-"

[books.zealot]
title = "Zealot"
author = "Reza Aslan"
format = "text"
genres = ["non-fiction"]
finished = 2023-03-24
media = "ebook"
via = "Libby"
grade = "B+"

[books.four-thousand-weeks]
title = "Four Thousand Weeks"
author = "Oliver Burkeman"
format = "text"
genres = ["non-fiction"]
finished = 2023-04-03
media = "ebook"
via = "Libby"
grade = "B"

[books.11-22-63]
title = "11/22/63: A Novel"
author = "Stephen King"
format = "text"
genres = ["science fiction"]
finished = 2023-04-14
media = "ebook"
via = "Libby"
grade = "A"
