[books.the-last-remains]
title = "The Last Remains"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2025-01-01
media = "ebook"
via = "Libby"
grade = "A-"

[books.stone-fruit]
title = "Stone Fruit"
author = "Lee Lai"
format = "graphic"
genres = ["fiction"]
finished = 2025-01-01
media = "paper"
via = "own"
grade = "A"

[books.karlas-choice]
title = "Karla's Choice"
author = "Nick Harkaway"
format = "text"
genres = ["spy"]
finished = 2025-01-14
media = "ebook"
via = "Libby"
grade = "A"

[books.the-true-believer]
title = "The True Believer"
author = "Eric Hoffer"
format = "text"
genres = ["non-fiction"]
finished = 2025-01-20
media = "paper"
via = "own"
grade = "A+"

[books.the-inner-game-of-tennis]
title = "The Inner Game of Tennis"
author = "W. Timothy Gallwey"
format = "text"
genres = ["non-fiction"]
finished = 2025-02-02
media = "paper"
via = "own"
grade = "A+"

[books.operation-wandering-soul]
title = "Operation Wandering Soul"
author = "Richard Powers"
format = "text"
genres = ["fiction"]
finished = 2025-02-11
media = "ebook"
via = "Libby"
grade = "B-"

[books.slough-horses]
title = "Slough Horses"
author = "Mick Herron"
format = "text"
genres = ["spy"]
finished = 2025-02-19
media = "ebook"
via = "Libby"
grade = "A"

[books.dead-lions]
title = "Dead Lions"
author = "Mick Herron"
format = "text"
genres = ["spy"]
finished = 2025-02-25
media = "ebook"
via = "Libby"
grade = "A"

[books.the-inner-game-of-ultimate-frisbee]
title = "The Inner Game of Ultimate Frisbee"
author = "Anthony David Adams"
format = "text"
genres = ["non-fiction"]
finished = 2025-03-08
media = "paper"
via = "own"
grade = "C-"

[books.the-three-body-problem]
title = "The Three-Body Problem"
author = "Cixin Liu"
format = "text"
genres = ["science fiction"]
finished = 2025-03-11
media = "ebook"
via = "Libby"
grade = "A"

[books.the-dark-forest]
title = "The Dark Forest"
author = "Cixin Liu"
format = "text"
genres = ["science fiction"]
finished = 2025-03-20
media = "ebook"
via = "Libby"
grade = "A-"

[books.deaths-end]
title = "Death's End"
author = "Cixin Liu"
format = "text"
genres = ["science fiction"]
finished = 2025-03-31
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-redemption-of-time]
title = "The Redemption of Time"
author = "Baoshu"
format = "text"
genres = ["science fiction"]
finished = 2025-04-07
media = "ebook"
via = "Libby"
grade = "C-"

[books.the-fifth-season]
title = "The Fifth Season"
author = "N.K. Jemisin"
format = "text"
genres = ["science fiction"]
finished = 2025-04-20
media = "ebook"
via = "Libby"
grade = "A"

[books.season-of-death]
title = "Season of Death"
author = "Will Thomas"
format = "text"
genres = ["mystery"]
finished = 2025-04-26
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-obselisk-gate]
title = "The Obelisk Gate"
author = "N.K. Jemisin"
format = "text"
genres = ["science fiction"]
finished = 2025-05-01
media = "ebook"
via = "Libby"
grade = "A"

[books.the-stone-sky]
title = "The Stone Sky"
author = "N.K. Jemisin"
format = "text"
genres = ["science fiction"]
finished = 2025-05-11
media = "ebook"
via = "Libby"
grade = "A"

[books.how-to-lie-with-maps]
title = "How to Lie with Maps"
author = "Mark Monmonier"
format = "text"
genres = ["non-fiction"]
finished = 2025-05-22
media = "paper"
via = "own"
grade = "A-"

[books.ball-lightning]
title = "Ball Lightning"
author = "Mick Herron"
format = "text"
genres = ["spy"]
finished = 2025-05-25
media = "ebook"
via = "Libby"
grade = "B+"

[books.real-tigers]
title = "Real Tigers"
author = "Mick Herron"
format = "text"
genres = ["spy"]
finished = 2025-06-04
media = "ebook"
via = "Libby"
grade = "A"
