[books.in-cold-blood]
title = "In Cold Blood"
author = "Truman Capote"
format = "text"
genres = ["true crime"]
finished = 2022-01-06
media = "ebook"
via = "Libby"
grade = "A-"

[books.bloodsucking-fiends]
title = "Bloodsucking Fiends"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-01-09
media = "ebook"
via = "Axis 360"
grade = "B+"

[books.seeing-with-fresh-eyes]
title = "Seeing With Fresh Eyes: Meaning - Space - Data - Truth"
author = "Edward Tufte"
format = "text"
genres = ["nonfiction"]
finished = 2022-01-16
media = "paper"
via = "own"
grade = "B"

[books.constant-gardener]
title = "The Constant Gardener"
author = "John Le Carré"
format = "text"
genres = ["suspense"]
finished = 2022-01-19
media = "paper"
via = "Little Library"
grade = "B+"

[books.you-suck]
title = "You Suck"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-01-25
media = "ebook"
via = "Axis 360"
grade = "B+"

[books.bite-me]
title = "Bite Me: A Love Story"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-02-01
media = "paper"
via = "own"
grade = "B"

[books.bobby-fishcer]
title = "Bobby Fischer Teaches Chess"
author = ["Bobby Fischer", "Stuart Margulies", "Donn Mosenfelder"]
format = "text"
genres = ["nonfiction"]
finished = 2022-02-02
media = "paper"
via = "own"
grade = "B+"

[books.the-plot]
title = "The Plot"
author = "Jean Hanff Korelitz"
format = "text"
genres = ["fiction"]
finished = 2022-02-05
media = "ebook"
via = "Libby"
grade = "A"

[books.grimms-fairy-tales]
title = "Grimm’s Fairy Tales"
author = ["Jacob Grimm", "Wilhelm Grimm"]
format = "text"
genres = ["fiction"]
finished = 2022-02-11
media = "ebook"
via = "Project Gutenberg"
grade = "B-"

[books.spymaster]
title = "Spymaster"
author = "Brad Thor"
format = "text"
genres = ["suspense"]
finished = 2022-02-11
media = "paper"
via = "Little Library"
grade = "C+"

[books.us-against-you]
title = "Us Against You"
author = "Fredrik Backman"
format = "text"
genres = ["fiction"]
finished = 2022-02-18
media = "ebook"
via = "Libby"
grade = "A"

[books.an-absolutely-remarkable-thing]
title = "An Absolutely Remarkable Thing"
author = "Hank Green"
format = "text"
genres = ["fiction"]
finished = 2022-02-24
media = "ebook"
via = "Libby"
grade = "A"

[books.a-beautifully-foolish-endeavor]
title = "A Beautifully Foolish Endeavor"
author = "Hank Green"
format = "text"
genres = ["fiction"]
finished = 2022-03-03
media = "ebook"
via = "Libby"
grade = "A"

[books.the-explainers-guide-to-number-sets]
title = "The Explainer’s Guide To Number Sets"
author = "Ronald T. Kneusel"
format = "text"
genres = ["nonfiction"]
finished = 2022-03-19
media = "ebook"
via = "author"
grade = "B+"

[books.notes-of-a-native-son]
title = "Notes of a Native Son"
author = "James Baldwin"
format = "text"
genres = ["nonfiction"]
finished = 2022-03-20
media = "paper"
via = "own"
grade = "A-"

[books.and-every-morning-the-way-home-gets-longer-and-longer]
title = "And Every Morning the Way Home Gets Longer and Longer"
author = "Fredrik Backman"
format = "text"
genres = ["fiction"]
finished = 2022-03-22
media = "ebook"
via = "Libby"
grade = "B"

[books.all-systems-red]
title = "All Systems Red (The Murderbot Diaries 1)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-03-24
media = "ebook"
via = "Libby"
grade = "A"

[books.holes]
title = "Holes"
author = "Louis Sachar"
format = "text"
genres = ["childrens"]
finished = 2022-04-04
media = "paper"
via = "borrowed"
grade = "B"

[books.stories-of-your-life-and-others]
title = "Stories of Your Life and Others"
author = "Ted Chiang"
format = "text"
genres = ["science fiction"]
finished = 2022-04-07
media = "ebook"
via = "Libby"
grade = "A+"

[books.these-truths]
title = "These Truths: A History of the United States"
author = "Jill Lepore"
format = "text"
genres = ["history"]
finished = 2022-04-16
media = "ebook"
via = "Libby"
grade = "B+"

[books.accidental-prime-minister]
title = "The Accidental Prime Minister"
author = "Tom McLaughlin"
format = "text"
genres = ["childrens"]
finished = 2022-04-17
media = "paper"
via = "borrowed"
grade = "C"

[books.artificial-condition]
title = "Artificial Condition (The Murderbot Diaries 2)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-04-19
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-big-sleep]
title = "The Big Sleep"
author = "Raymond Chandler"
format = "text"
genres = ["detective"]
finished = 2022-04-25
media = "ebook"
via = "Libby"
grade = "B"

[books.the-artists-way]
title = "The Artist's Way: A Spiritual Path to Higher Creativity"
author = "Julia Cameron"
format = "text"
genres = ["self-help"]
finished = 2022-04-29
media = "paper"
via = "own"
grade = "A"

[books.the-pragmatic-programmer]
title = "The Pragmatic Programmer: Your Journey to Mastery (20th Anniversary Edition)"
author = ["David Thomas", "Andrew Hunt"]
format = "text"
genres = ["computer"]
finished = 2022-05-06
media = "paper"
via = "own"
grade = "A+"
