[books.anthropica]
title = "Anthropica"
author = "David Hollander"
format = "text"
genres = ["fiction"]
finished = 2023-01-01
media = "paper"
via = "own"
grade = "B"

[books.sixteen-ways-to-defend-a-walled-city]
title = "Sixteen Ways to Defend a Walled City"
author = "K. J. Parker"
format = "text"
genres = ["fantasy"]
finished = 2023-01-09
media = "paper"
via = "Boulder Public Library"
grade = "A"

[books.the-echo-maker]
title = "The Echo Maker"
author = "Richard Powers"
format = "text"
genres = ["mystery"]
finished = 2023-01-19
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-winners]
title = "The Winners"
author = "Fredrik Backman"
format = "text"
genres = ["fiction"]
finished = 2023-01-31
media = "ebook"
via = "own"
grade = "A"

[books.critical-mass]
title = "Critical Mass"
author = "Daniel Suarez"
format = "text"
genres = ["science fiction"]
finished = 2023-03-02
media = "ebook"
via = "own"
grade = "B"

[books.how-to-rule-an-empire]
title = "How to Rule an Empire and Get Away with it"
author = "K. J. Parker"
format = "text"
genres = ["fantasy"]
finished = 2023-03-07
media = "paper"
via = "Boulder Public Library"
grade = "B+"

[books.the-blade-itself]
title = "The Blade Itself"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-03-22
media = "ebook"
via = "Libby"
grade = "A-"

[books.zealot]
title = "Zealot"
author = "Reza Aslan"
format = "text"
genres = ["non-fiction"]
finished = 2023-03-24
media = "ebook"
via = "Libby"
grade = "B+"

[books.four-thousand-weeks]
title = "Four Thousand Weeks"
author = "Oliver Burkeman"
format = "text"
genres = ["non-fiction"]
finished = 2023-04-03
media = "ebook"
via = "Libby"
grade = "B"

[books.11-22-63]
title = "11/22/63: A Novel"
author = "Stephen King"
format = "text"
genres = ["science fiction"]
finished = 2023-04-14
media = "ebook"
via = "Libby"
grade = "A"

[books.a-practical-guide-to-conquering-the-world]
title = "A Practical Guide to Conquering the World"
author = "K. J. Parker"
format = "text"
genres = ["fantasy"]
finished = 2023-04-22
media = "paper"
via = "Jefferson County Public Library"
grade = "A"

[books.before-they-are-hanged]
title = "Before They Are Hanged"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-05-06
media = "ebook"
via = "Libby"
grade = "A-"

[books.built-to-move]
title = "Built to Move"
author = ["Kelly Starrett", "Juliet Starrett"]
format = "text"
genres = ["non-fiction"]
finished = 2023-05-11
media = "paper"
via = "own"
grade = "A-"

[books.last-argument-of-kings]
title = "Last Argument of Kings"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-05-22
media = "ebook"
via = "Libby"
grade = "A-"

[books.there-are-no-accidents]
title = "There Are No Accidents"
author = "Jessie Singer"
format = "text"
genres = ["non-fiction"]
finished = 2023-05-22
media = "paper"
via = "Boulder Public Library"
grade = "A"

[books.best-served-cold]
title = "Best Served Cold"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-06-26
media = "ebook"
via = "Libby"
grade = "B+"

[books.the-crossing-spaces]
title = "The Crossing Spaces"
author = "Elly Griffith"
format = "text"
genres = ["mystery"]
finished = 2023-06-29
media = "ebook"
via = "Libby"
grade = "B+"

[books.a-deadly-education]
title = "A Deadly Education"
author = "Naomi Novik"
format = "text"
genres = ["fantasy"]
finished = 2023-07-02
media = "ebook"
via = "Libby"
grade = "A"

[books.yearning-for-the-impossible]
title = "Yearning for the Impossible"
author = ["John Stillwell"]
format = "text"
genres = ["non-fiction"]
finished = 2023-07-08
media = "paper"
via = "own"
grade = "A-"

[books.the-last-graduate]
title = "The Last Graduate"
author = "Naomi Novik"
format = "text"
genres = ["fantasy"]
finished = 2023-07-09
media = "ebook"
via = "Libby"
grade = "A"

[books.the-golden-enclaves]
title = "The Golden Enclaves"
author = "Naomi Novik"
format = "text"
genres = ["fantasy"]
finished = 2023-07-07
media = "ebook"
via = "Libby"
grade = "A"

[books.the-heroes]
title = "The Heroes"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-08-06
media = "ebook"
via = "Libby"
grade = "B+"

[books.the-book-of-five-rings]
title = "The Book of Five Rings"
author = "Miyamoto Musashi"
format = "text"
genres = ["non-fiction"]
finished = 2023-08-11
media = "ebook"
via = "own"
grade = "C"

[books.red-country]
title = "Red Country"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-08-19
media = "ebook"
via = "Libby"
grade = "B"

[books.the-witch-king]
title = "The Witch King"
author = "Martha Wells"
format = "text"
genres = ["fantasy"]
finished = 2023-08-25
media = "ebook"
via = "Libby"
grade = "A"

[books.th-kaiju-preservation-society]
title = "The Kaiju Preservation Society"
author = "John Scalzi"
format = "text"
genres = ["fantasy"]
finished = 2023-08-25
media = "ebook"
via = "Libby"
grade = "B+"

[books.glucose-revolution]
title = "Glucose Revolution"
author = "Jessie Inchauspé"
format = "text"
genres = ["non-fiction"]
finished = 2023-09-10
media = "paper"
via = "Jefferson County Public Library"
grade = "A"

[books.sharp-ends]
title = "Sharp Ends"
author = "Joe Abercrombie"
format = "text"
genres = ["fantasy"]
finished = 2023-09-15
media = "ebook"
via = "Libby"
grade = "B+"

[books.some-danger-involved]
title = "Some Danger Involved"
author = "Will Thomas"
format = "text"
genres = ["mystery"]
finished = 2023-09-22
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-last-devil-to-die]
title = "The Last Devil to Die"
author = "Richard Osman"
format = "text"
genres = ["mystery"]
finished = 2023-09-28
media = "ebook"
via = "Libby"
grade = "A"

[books.redshirts]
title = "Redshirts"
author = "John Scalzi"
format = "text"
genres = ["science fiction"]
finished = 2023-10-02
media = "ebook"
via = "Libby"
grade = "B"

[books.the-art-thief]
title = "The Art Thief"
author = "Michael Finkel"
format = "text"
genres = ["non-fiction"]
finished = 2023-10-05
media = "ebook"
via = "Libby"
grade = "B+"

[books.the-100-year-old-man-who-climbed-out-the-window-and-disappeared]
title = "The 100-Year-Old Man Who Climbed Out the Window and Disappeared"
author = "Jonas Jonasson"
format = "text"
genres = ["non-fiction"]
finished = 2023-10-14
media = "ebook"
via = "Libby"
grade = "B"

[books.elder-race]
title = "Elder Race"
author = "Adrian Tchaikovsky"
format = "text"
genres = ["science fiction", "fantasy"]
finished = 2023-10-17
media = "ebook"
via = "Libby"
grade = "A+"

[books.the-creative-act]
title = "The Creative Act"
author = ["Rick Rubin"]
format = "text"
genres = ["non-fiction"]
finished = 2023-10-18
media = "paper"
via = "own"
grade = "B-"
