[books.the-last-remains]
title = "The Last Remains"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2025-01-01
media = "ebook"
via = "Libby"
grade = "A-"

[books.stone-fruit]
title = "Stone Fruit"
author = "Lee Lai"
format = "graphic"
genres = ["fiction"]
finished = 2025-01-01
media = "paper"
via = "own"
grade = "A"

[books.karlas-choice]
title = "Karla's Choice"
author = "Nick Harkaway"
format = "text"
genres = ["spy"]
finished = 2025-01-14
media = "ebook"
via = "Libby"
grade = "A"

[books.the-true-believer]
title = "The True Believer"
author = "Eric Hoffer"
format = "text"
genres = ["non-fiction"]
finished = 2025-01-20
media = "paper"
via = "own"
grade = "A+"

[books.the-inner-game-of-tennis]
title = "The Inner Game of Tennis"
author = "W. Timothy Gallwey"
format = "text"
genres = ["non-fiction"]
finished = 2025-02-02
media = "paper"
via = "own"
grade = "A+"

[books.operation-wandering-soul]
title = "Operation Wandering Soul"
author = "Richard Powers"
format = "text"
genres = ["fiction"]
finished = 2025-02-11
media = "ebook"
via = "Libby"
grade = "B-"
