[books.the-last-remains]
title = "The Last Remains"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2025-01-01
media = "ebook"
via = "Libby"
grade = "A-"

[books.stone-fruit]
title = "Stone Fruit"
author = "Lee Lai"
format = "graphic"
genres = ["fiction"]
finished = 2025-01-01
media = "paper"
via = "Libby"
grade = "A"
