[books.in-cold-blood]
title = "In Cold Blood"
author = "Truman Capote"
format = "text"
genres = ["true crime"]
finished = 2022-01-06
media = "ebook"
via = "Libby"
grade = "A-"

[books.bloodsucking-fiends]
title = "Bloodsucking Fiends"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-01-09
media = "ebook"
via = "Axis 360"
grade = "B+"

[books.seeing-with-fresh-eyes]
title = "Seeing With Fresh Eyes: Meaning - Space - Data - Truth"
author = "Edward Tufte"
format = "text"
genres = ["nonfiction"]
finished = 2022-01-16
media = "paper"
via = "own"
grade = "B"

[books.constant-gardener]
title = "The Constant Gardener"
author = "John Le Carré"
format = "text"
genres = ["fiction"]
finished = 2022-01-19
media = "paper"
via = "Little Library"
grade = "B+"

[books.you-suck]
title = "You Suck"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-01-25
media = "ebook"
via = "Axis 360"
grade = "B+"

[books.bite-me]
title = "Bite Me: A Love Story"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-02-01
media = "paper"
via = "own"
grade = "B"

[books.bobby-fishcer]
title = "Bobby Fischer Teaches Chess"
author = ["Bobby Fischer", "Stuart Margulies", "Donn Mosenfelder"]
format = "text"
genres = ["nonfiction"]
finished = 2022-02-02
media = "paper"
via = "own"
grade = "B+"

[books.the-plot]
title = "The Plot"
author = "Jean Hanff Korelitz"
format = "text"
genres = ["fiction"]
finished = 2022-02-05
media = "ebook"
via = "Libby"
grade = "A"

[books.grimms-fairy-tales]
title = "Grimm’s Fairy Tales"
author = ["Jacob Grimm", "Wilhelm Grimm"]
format = "text"
genres = ["fiction"]
finished = 2022-02-11
media = "ebook"
via = "Project Gutenberg"
grade = "B-"

[books.spymaster]
title = "Spymaster"
author = "Brad Thor"
format = "text"
genres = ["fiction"]
finished = 2022-02-11
media = "paper"
via = "Little Library"
grade = "C+"

[books.us-against-you]
title = "Us Against You"
author = "Fredrik Backman"
format = "text"
genres = ["fiction"]
finished = 2022-02-18
media = "ebook"
via = "Libby"
grade = "A"

[books.an-absolutely-remarkable-thing]
title = "An Absolutely Remarkable Thing"
author = "Hank Green"
format = "text"
genres = ["science fiction"]
finished = 2022-02-24
media = "ebook"
via = "Libby"
grade = "A"

[books.a-beautifully-foolish-endeavor]
title = "A Beautifully Foolish Endeavor"
author = "Hank Green"
format = "text"
genres = ["science fiction"]
finished = 2022-03-03
media = "ebook"
via = "Libby"
grade = "A"

[books.the-explainers-guide-to-number-sets]
title = "The Explainer’s Guide To Number Sets"
author = "Ronald T. Kneusel"
format = "text"
genres = ["nonfiction"]
finished = 2022-03-19
media = "ebook"
via = "author"
grade = "B+"

[books.notes-of-a-native-son]
title = "Notes of a Native Son"
author = "James Baldwin"
format = "text"
genres = ["nonfiction"]
finished = 2022-03-20
media = "paper"
via = "own"
grade = "A-"

[books.and-every-morning-the-way-home-gets-longer-and-longer]
title = "And Every Morning the Way Home Gets Longer and Longer"
author = "Fredrik Backman"
format = "text"
genres = ["fiction"]
finished = 2022-03-22
media = "ebook"
via = "Libby"
grade = "B"

[books.all-systems-red]
title = "All Systems Red (The Murderbot Diaries 1)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-03-24
media = "ebook"
via = "Libby"
grade = "A"

[books.holes]
title = "Holes"
author = "Louis Sachar"
format = "text"
genres = ["childrens"]
finished = 2022-04-04
media = "paper"
via = "borrowed"
grade = "B"

[books.stories-of-your-life-and-others]
title = "Stories of Your Life and Others"
author = "Ted Chiang"
format = "text"
genres = ["science fiction"]
finished = 2022-04-07
media = "ebook"
via = "Libby"
grade = "A+"

[books.these-truths]
title = "These Truths: A History of the United States"
author = "Jill Lepore"
format = "text"
genres = ["nonfiction"]
finished = 2022-04-16
media = "ebook"
via = "Libby"
grade = "B+"

[books.accidental-prime-minister]
title = "The Accidental Prime Minister"
author = "Tom McLaughlin"
format = "text"
genres = ["childrens"]
finished = 2022-04-17
media = "paper"
via = "borrowed"
grade = "C"

[books.artificial-condition]
title = "Artificial Condition (The Murderbot Diaries 2)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-04-19
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-big-sleep]
title = "The Big Sleep"
author = "Raymond Chandler"
format = "text"
genres = ["mystery"]
finished = 2022-04-25
media = "ebook"
via = "Libby"
grade = "B"

[books.the-artists-way]
title = "The Artist's Way: A Spiritual Path to Higher Creativity"
author = "Julia Cameron"
format = "text"
genres = ["self-help"]
finished = 2022-04-29
media = "paper"
via = "own"
grade = "A"

[books.the-pragmatic-programmer]
title = "The Pragmatic Programmer: Your Journey to Mastery (20th Anniversary Edition)"
author = ["David Thomas", "Andrew Hunt"]
format = "text"
genres = ["nonfiction"]
finished = 2022-05-06
media = "paper"
via = "own"
grade = "A+"

[books.the-windup-girl]
title = "The Windup Girl"
author = "Paolo Bacigalupi"
format = "text"
genres = ["science fiction"]
finished = 2022-05-13
media = "ebook"
via = "Libby"
grade = "A+"

[books.the-book-of-accidents]
title = "The Book of Accidents"
author = "Chuck Wendig"
format = "text"
genres = ["horror"]
finished = 2022-05-15
media = "ebook"
via = "Libby"
grade = "B-"

[books.rogue-protocol]
title = "Rogue Protocol (The Murderbot Diaries 3)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-05-17
media = "ebook"
via = "Libby"
grade = "A"

[books.the-thursday-murder-club]
title = "The Thursday Murder Club"
author = "Richard Osman"
format = "text"
genres = ["mystery"]
finished = 2022-05-23
media = "ebook"
via = "Libby"
grade = "A"

[books.the-tyranny-of-metrics]
title = "The Tyranny of Metrics"
author = "Jerry Z. Muller"
format = "text"
genres = ["nonfiction"]
finished = 2022-06-04
media = "paper"
via = "own"
grade = "A-"

[books.midnight-riot]
title = "Midnight Riot (Rivers of London #1)"
author = "Ben Aaronvitch"
format = "text"
genres = ["mystery"]
finished = 2022-06-04
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.the-overstory]
title = "The Overstory"
author = "Richard Powers"
format = "text"
genres = ["fiction"]
finished = 2022-06-17
media = "paper"
via = "own"
grade = "A+"

[books.exit-strategy]
title = "Exit Strategy (The Murderbot Diaries 4)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-06-20
media = "ebook"
via = "Libby"
grade = "A"

[books.the-book]
title = "The Book"
author = "Alan W. Watts"
format = "text"
genres = ["nonfiction"]
finished = 2022-06-21
media = "paper"
via = "own"
grade = "A-"

[books.the-man-who-died-twice]
title = "The Man Who Died Twice (A Thursday Murder Club Mystery)"
author = "Richard Osman"
format = "text"
genres = ["mystery"]
finished = 2022-06-23
media = "ebook"
via = "Libby"
grade = "A-"

[books.network-effect]
title = "Network Effect (The Murderbot Diaries 5)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-07-04
media = "ebook"
via = "Libby"
grade = "A"

[books.fugitive-telemetry]
title = "Fugitive Telemetry (The Murderbot Diaries 6)"
author = "Martha Wells"
format = "text"
genres = ["science fiction"]
finished = 2022-07-07
media = "ebook"
via = "Libby"
grade = "A-"

[books.piranesi]
title = "Piranese"
author = "Susanna Clarke"
format = "text"
genres = ["science fiction"]
finished = 2022-07-11
media = "ebook"
via = "Libby"
grade = "A"

[books.goblin-emperor]
title = "The Goblin Emperor"
author = "Katherine Addison"
format = "text"
genres = ["fantasy"]
finished = 2022-07-23
media = "ebook"
via = "Libby"
grade = "B+"

[books.fast-kids-dont-train-slow]
title = "Fast Kids Don't Train Slow"
author = "Dunte Hector"
format = "text"
genres = ["nonfiction"]
finished = 2022-08-04
media = "paper"
via = "own"
grade = "B+"

[books.witness-for-the-dead]
title = "Witness for the Dead"
author = "Katherine Addison"
format = "text"
genres = ["fantasy"]
finished = 2022-08-06
media = "ebook"
via = "Libby"
grade = "A-"

[books.mathematics-for-human-flourishing]
title = "Mathematics for Human Flourishing"
author = "Francis Su"
format = "text"
genres = ["nonfiction"]
finished = 2022-08-07
media = "paper"
via = "Boulder Public Library"
grade = "A"

[books.among-others]
title = "Among Others"
author = "Jo Walton"
format = "text"
genres = ["fantasy"]
finished = 2022-08-16
media = "ebook"
via = "Libby"
grade = "A"

[books.journey-through-genius]
title = "Journey through Genius"
author = "William Dunham"
format = "text"
genres = ["nonfiction"]
finished = 2022-08-29
media = "paper"
via = "own"
grade = "A+"

[books.what-if-2]
title = "What If? 2"
author = "Randall Munroe"
format = "text"
genres = ["nonfiction"]
finished = 2022-09-22
media = "paper"
via = "own"
grade = "A"

[books.bridge-to-terabithia]
title = "Bridge to Terabithia"
author = "Katherine Paterson"
format = "text"
genres = ["childrens"]
finished = 2022-09-23
media = "paper"
via = "borrowed"
grade = "A"

[books.the-steerswoman]
title = "The Steerswoman"
author = "Rosemary Kirstein"
format = "text"
genres = ["fantasy", "science fiction"]
finished = 2022-10-10
media = "ebook"
via = "own"
grade = "A-"

[books.the-outskirters-secret]
title = "The Outskirter’s Secret"
author = "Rosemary Kirstein"
format = "text"
genres = ["fantasy", "science fiction"]
finished = 2022-10-13
media = "ebook"
via = "own"
grade = "A-"

[books.the-lost-steersman]
title = "The Lost Steersman"
author = "Rosemary Kirstein"
format = "text"
genres = ["fantasy", "science fiction"]
finished = 2022-10-22
media = "ebook"
via = "own"
grade = "A-"

[books.the-language-of-power]
title = "The Language of Power"
author = "Rosemary Kirstein"
format = "text"
genres = ["fantasy", "science fiction"]
finished = 2022-10-25
media = "ebook"
via = "own"
grade = "A-"

[books.ink-black-heart]
title = "The Ink Black Heart"
author = "Robert Galbraith"
format = "text"
genres = ["mystery"]
finished = 2022-11-11
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.bewilderment]
title = "Bewilderment"
author = "Richard Powers"
format = "text"
genres = ["fiction"]
finished = 2022-11-19
media = "paper"
via = "own"
grade = "A+"
