[books.ready-player-two]
title = "Ready Player Two"
author = "Ernest Cline"
format = "text"
genres = ["science fiction"]
finished = 2021-01-03
media = "paper"
via = "Boulder Public Library"
grade = "B+"

[books.forever-war]
title = "Forever War"
author = "Joe Haldeman"
format = "text"
genres = ["science fiction"]
finished = 2021-01-10
media = "ebook"
via = "Libby"
grade = "B"

[books.wonder-woman]
title = "The Secret History of Wonder Woman"
author = "Jill Lepore"
format = "text"
genres = ["non-fiction"]
finished = 2021-01-19
media = "ebook"
via = "Libby"
grade = "B+"

[books.five-on-a-treasure-island]
title = "The Famous Five: Five on a Treasure Island"
author = "Enid Blyton"
format = "text"
genres = ["childrens"]
finished = 2021-01-22
media = "paper"
via = "borrowed"
grade = "B"

[books.inktober]
title = "Inktober All Year Long"
author = "Jake Parker"
format = "text"
genres = ["non-fiction"]
finished = 2021-01-23
media = "paper"
via = "own"
grade = "B+"

[books.lexicon]
title = "Lexicon"
author = "Max Barry"
format = "text"
genres = ["science fiction"]
finished = 2021-01-26
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-sun]
title = "The Sun: A Very Short Introduction"
author = "Philip Judge"
format = "text"
genres = ["non-fiction"]
finished = 2021-02-06
media = "paper"
via = "own"
grade = "B"

[books.farmer-brown]
title = "Farmer Brown"
author = ["Dave Closser", "Brigit Galloy"]
format = "graphic"
genres = ["childrens"]
finished = 2021-02-21
media = "paper"
via = "own"
grade = "C"

[books.things-i-wish-id-known]
title = "Things I Wish I'd Known: Cancer Caregivers Speak Out"
author = "Deborah J. Cornwall"
format = "text"
genres = ["self-help"]
finished = 2021-02-23
media = "paper"
via = "Boulder Public Library"
grade = "B+"

[books.righteous-mind]
title = "The Righteous Mind: Why Good People Are Divided by Politics and Religion"
author = "Jonathan Haidt"
format = "text"
genres = ["non-fiction"]
finished = 2021-02-28
media = "ebook"
via = "Libby"
grade = "A-"

[books.pen-ink-drawing]
title = "Pen & Ink Drawing: A Simple Guide"
author = "Alphonso Dunn"
format = "text"
genres = ["non-fiction"]
finished = 2021-03-19
media = "paper"
via = "own"
grade = "A-"

[books.black-prism]
title = "The Black Prism"
author = "Brent Weeks"
format = "text"
genres = ["fantasy"]
finished = 2021-03-31
media = "paper"
via = "own"
grade = "B+"

[books.naked-sun]
title = "The Naked Sun"
author = "Isaac Asimov"
format = "text"
genres = ["science fiction"]
finished = 2021-04-07
media = "paper"
via = "Boulder Public Library"
grade = "B+"

[books.blinding-knife]
title = "The Blinding Knife"
author = "Brent Weeks"
format = "text"
genres = ["fantasy"]
finished = 2021-05-14
media = "paper"
via = "Boulder Public Library"
grade = "B+"

[books.broken-eye]
title = "The Broken Eye"
author = "Brent Weeks"
format = "audio"
genres = ["fantasy"]
finished = 2021-05-24
media = "ebook"
via = "Libby"
grade = "A-"

[books.99-invisible-city]
title = "The 99% Invisible City: A Field Guid to the Hidden World of Everyday Design"
author = ["Roman Mars", "Kurt Kohlstedt"]
format = "text"
genres = ["non-fiction"]
finished = 2021-05-28
media = "paper"
via = "own"
grade = "A"

[books.modern-art]
title = "Modern Art"
author = "Hans Werner Holzwarth"
format = "text"
genres = ["non-fiction"]
finished = 2021-05-29
media = "paper"
via = "own"
grade = "B"

[books.why-art]
title = "Why Art?"
author = "Eleanor Davis"
format = "text"
genres = ["non-fiction"]
finished = 2021-05-30
media = "paper"
via = "own"
grade = "C+"

[books.tower-treasure]
title = "The Tower Treasure"
author = "Franklin W. Dixon"
format = "text"
genres = ["mystery"]
finished = 2021-05-31
media = "paper"
via = "Arvada Public Library"
grade = "B"

[books.distracted-mind]
title = "The Distracted Mind: Ancient Brains in a High-Tech World"
author = ["Adam Gazzaley", "Larry D. Rosen"]
format = "text"
genres = ["non-fiction"]
finished = 2021-06-09
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.visual-intelligence]
title = "Visual Intelligence: Sharpen Your Perception, Change Your Life"
author = "Amy E. Herman"
format = "text"
genres = ["non-fiction"]
finished = 2021-06-17
media = "paper"
via = "own"
grade = "B+"

[books.blood-mirror]
title = "The Blood Mirror"
author = "Brent Weeks"
format = "text"
genres = ["fantasy"]
finished = 2021-07-04
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.surveillance-capitalism]
title = "How to Destroy 'Surveillance Capitalism'"
author = "Cory Doctorow"
format = "text"
genres = ["non-fiction"]
finished = 2021-07-14
media = "ebook"
via = "web"
grade = "A-"

[books.burning-white]
title = "The Burning White"
author = "Brent Weeks"
format = "text"
genres = ["fantasy"]
finished = 2021-08-10
media = "paper"
via = "Boulder Public Library"
grade = "B"

[books.project-hail-mary]
title = "Project Hail Mary"
author = "Andy Weir"
format = "text"
genres = ["science fiction"]
finished = 2021-08-30
media = "ebook"
via = "Libby"
grade = "A-"

[books.suburban-nation]
title = "Suburban Nation: Rise of Sprawl and the Decline of the American Dream"
author = "Andres Duany, Elizabeth Plater-Zyberk, and Jeff Speck"
format = "text"
genres = ["non-fiction"]
finished = 2021-09-06
media = "paper"
via = "Boulder Public Library"
grade = "A"

[books.station-eleven]
title = "Station Eleven"
author = "Emily St. John Mandel"
format = "text"
genres = ["science fiction"]
finished = 2021-09-18
media = "ebook"
via = "Libby"
grade = "B+"

[books.lightning-thief]
title = "The Lightning Thief"
author = "Rick Riordan"
format = "text"
genres = ["fantasy"]
finished = 2021-09-25
media = "paper"
via = "borrowed"
grade = "B-"

[books.the-dispossessed]
title = "The Dispossessed"
author = "Ursula K. Le Guin"
format = "text"
genres = ["science fiction"]
finished = 2020-10-17
media = "ebook"
via = "Hoopla"
grade = "A"