[books.ready-player-two]
title = "Ready Player Two"
author = "Ernest Cline"
format = "text"
genres = ["science fiction"]
finished = 2021-01-03
media = "paper"
via = "Boulder Public Library"
grade = "B+"

[books.forever-war]
title = "Forever War"
author = "Joe Haldeman"
format = "text"
genres = ["science fiction"]
finished = 2021-01-10
media = "ebook"
via = "Libby"
grade = "B"

[books.wonder-woman]
title = "The Secret History of Wonder Woman"
author = "Jill Lepore"
format = "text"
genres = ["non-fiction"]
finished = 2021-01-19
media = "ebook"
via = "Libby"
grade = "B+"

[books.five-on-a-treasure-island]
title = "The Famous Five: Five on a Treasure Island"
author = "Enid Blyton"
format = "text"
genres = ["childrens"]
finished = 2021-01-22
media = "paper"
via = "borrowed"
grade = "B"

[books.inktober]
title = "Inktober All Year Long"
author = "Jake Parker"
format = "text"
genres = ["non-fiction"]
finished = 2021-01-23
media = "paper"
via = "own"
grade = "B+"

[books.lexicon]
title = "Lexicon"
author = "Max Barry"
format = "text"
genres = ["science fiction"]
finished = 2021-01-26
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-sun]
title = "The Sun: A Very Short Introduction"
author = "Philip Judge"
format = "text"
genres = ["non-fiction"]
finished = 2021-02-06
media = "paper"
via = "own"
grade = "B"

[books.farmer-brown]
title = "Farmer Brown"
author = ["Dave Closser", "Brigit Galloy"]
format = "text"
genres = ["childrens"]
finished = 2021-02-21
media = "paper"
via = "own"
grade = "C"

[books.things-i-wish-id-known]
title = "Things I Wish I'd Known: Cancer Caregivers Speak Out"
author = "Deborah J. Cornwall"
format = "text"
genres = ["self-help"]
finished = 2021-02-23
media = "paper"
via = "Boulder Public Library"
grade = "B+"
