[books.going-infinite]
title = "Going Infinite"
author = "Michael Lewis"
format = "text"
genres = ["non-fiction"]
finished = 2024-01-01
media = "ebook"
via = "Libby"
grade = "B+"

[books.dad-jokes]
title = "Dad Jokes: The Good. The Bad. The Terrible."
author = ["Jimmy Niro"]
format = "text"
genres = ["non-fiction"]
finished = 2024-01-01
media = "paper"
via = "own"
grade = "B-"

[books.mae-volume-one]
title = "Mae: Volume One"
author = ["Gene Ha"]
format = "graphic"
genres = ["fantasy"]
finished = 2024-01-05
media = "paper"
via = "borrowed"
grade = "B-"

[books.the-spare-man]
title = "The Spare Man"
author = "Mary Robinette Kowal"
format = "text"
genres = ["fantasy"]
finished = 2024-01-07
media = "ebook"
via = "Libby"
grade = "A-"

[books.hell-bay]
title = "Hell Bay"
author = "Will Thomas"
format = "text"
genres = ["mystery"]
finished = 2024-01-11
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-murder-of-roger-ackroyd]
title = "The Murder of Roger Ackroyd"
author = "Agatha Christie"
format = "text"
genres = ["mystery"]
finished = 2024-01-13
media = "ebook"
via = "Libby"
grade = "A"

[books.old-scores]
title = "Old Scores"
author = "Will Thomas"
format = "text"
genres = ["mystery"]
finished = 2024-01-18
media = "ebook"
via = "Libby"
grade = "A-"

[books.bookshops-and-onedust]
title = "Bookshops & Bonedust"
author = "Travis Baldree"
format = "text"
genres = ["fantasy"]
finished = 2024-01-26
media = "ebook"
via = "Libby"
grade = "B+"

[books.thornhedge]
title = "Thornhedge"
author = "T. Kingfisher"
format = "text"
genres = ["fantasy"]
finished = 2024-01-29
media = "ebook"
via = "Libby"
grade = "A"

[books.tomorrow-and-tomorrow-and-tomorrow]
title = "Tomorrow, and Tomorrow, and Tomorrow"
author = "Gabrielle Zevin"
format = "text"
genres = ["fiction"]
finished = 2024-02-07
media = "ebook"
via = "Libby"
grade = "A+"

[books.for-we-are-many]
title = "For We Are Many"
author = "Dennis E. Taylor"
format = "text"
genres = ["science fiction"]
finished = 2024-02-11
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.the-janus-stone]
title = "The Janus Stone"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-02-12
media = "ebook"
via = "Libby"
grade = "A-"

[books.all-these-worlds]
title = "All These Worlds"
author = "Dennis E. Taylor"
format = "text"
genres = ["science fiction"]
finished = 2024-02-17
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.wild-fermentation]
title = "Wild Fermentation"
author = ["Sandor Ellix Katz"]
format = "text"
genres = ["non-fiction"]
finished = 2024-02-19
media = "paper"
via = "own"
grade = "A"

[books.you-feel-it-just-below-the-ribs]
title = "You Feel It Just Below the Ribs"
author = ["Jeffrey Cranor", "Janina Matthewson"]
format = "text"
genres = ["fiction"]
finished = 2024-02-19
media = "ebook"
via = "Libby"
grade = "A"

[books.venomous-lumpsucker]
title = "Venomous Lumpsucker"
author = ["Ned Beauman"]
format = "text"
genres = ["fiction"]
finished = 2024-02-26
media = "ebook"
via = "Libby"
grade = "A"

[books.blood-is-blood]
title = "Blood is Blood"
author = ["Will Thomas"]
format = "text"
genres = ["mystery"]
finished = 2024-03-01
media = "ebook"
via = "Libby"
grade = "A-"
