[books.going-infinite]
title = "Going Infinite"
author = "Michael Lewis"
format = "text"
genres = ["non-fiction"]
finished = 2024-01-01
media = "ebook"
via = "Libby"
grade = "B+"

[books.dad-jokes]
title = "Dad Jokes: The Good. The Bad. The Terrible."
author = ["Jimmy Niro"]
format = "text"
genres = ["non-fiction"]
finished = 2024-01-01
media = "paper"
via = "own"
grade = "B-"

[books.mae-volume-one]
title = "Mae: Volume One"
author = ["Gene Ha"]
format = "graphic"
genres = ["fantasy"]
finished = 2024-01-05
media = "paper"
via = "borrowed"
grade = "B-"

[books.the-spare-man]
title = "The Spare Man"
author = "Mary Robinette Kowal"
format = "text"
genres = ["fantasy"]
finished = 2024-01-07
media = "ebook"
via = "Libby"
grade = "A-"

[books.hell-bay]
title = "Hell Bay"
author = "Will Thomas"
format = "text"
genres = ["mystery"]
finished = 2024-01-11
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-murder-of-roger-ackroyd]
title = "The Murder of Roger Ackroyd"
author = "Agatha Christie"
format = "text"
genres = ["mystery"]
finished = 2024-01-13
media = "ebook"
via = "Libby"
grade = "A"

[books.old-scores]
title = "Old Scores"
author = "Will Thomas"
format = "text"
genres = ["mystery"]
finished = 2024-01-18
media = "ebook"
via = "Libby"
grade = "A-"

[books.bookshops-and-onedust]
title = "Bookshops & Bonedust"
author = "Travis Baldree"
format = "text"
genres = ["fantasy"]
finished = 2024-01-26
media = "ebook"
via = "Libby"
grade = "B+"

[books.thornhedge]
title = "Thornhedge"
author = "T. Kingfisher"
format = "text"
genres = ["fantasy"]
finished = 2024-01-29
media = "ebook"
via = "Libby"
grade = "A"

[books.tomorrow-and-tomorrow-and-tomorrow]
title = "Tomorrow, and Tomorrow, and Tomorrow"
author = "Gabrielle Zevin"
format = "text"
genres = ["fiction"]
finished = 2024-02-07
media = "ebook"
via = "Libby"
grade = "A+"

[books.for-we-are-many]
title = "For We Are Many"
author = "Dennis E. Taylor"
format = "text"
genres = ["science fiction"]
finished = 2024-02-11
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.the-janus-stone]
title = "The Janus Stone"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-02-12
media = "ebook"
via = "Libby"
grade = "A-"

[books.all-these-worlds]
title = "All These Worlds"
author = "Dennis E. Taylor"
format = "text"
genres = ["science fiction"]
finished = 2024-02-17
media = "paper"
via = "Boulder Public Library"
grade = "A-"

[books.wild-fermentation]
title = "Wild Fermentation"
author = ["Sandor Ellix Katz"]
format = "text"
genres = ["non-fiction"]
finished = 2024-02-19
media = "paper"
via = "own"
grade = "A"

[books.you-feel-it-just-below-the-ribs]
title = "You Feel It Just Below the Ribs"
author = ["Jeffrey Cranor", "Janina Matthewson"]
format = "text"
genres = ["fiction"]
finished = 2024-02-19
media = "ebook"
via = "Libby"
grade = "A"

[books.venomous-lumpsucker]
title = "Venomous Lumpsucker"
author = ["Ned Beauman"]
format = "text"
genres = ["fiction"]
finished = 2024-02-26
media = "ebook"
via = "Libby"
grade = "A"

[books.blood-is-blood]
title = "Blood is Blood"
author = ["Will Thomas"]
format = "text"
genres = ["mystery"]
finished = 2024-03-01
media = "ebook"
via = "Libby"
grade = "A-"

[books.lethal-pursuit]
title = "Lethal Pursuit"
author = ["Will Thomas"]
format = "text"
genres = ["mystery"]
finished = 2024-03-04
media = "ebook"
via = "Libby"
grade = "A-"

[books.dance-with-death]
title = "Dance with Death"
author = ["Will Thomas"]
format = "text"
genres = ["mystery"]
finished = 2024-03-11
media = "ebook"
via = "Libby"
grade = "A-"

[books.fierce-poison]
title = "Fierce Poison"
author = ["Will Thomas"]
format = "text"
genres = ["mystery"]
finished = 2024-03-16
media = "ebook"
via = "Libby"
grade = "A-"

[books.heart-of-the-nile]
title = "Heart of the Nile"
author = ["Will Thomas"]
format = "text"
genres = ["mystery"]
finished = 2024-03-23
media = "ebook"
via = "Libby"
grade = "A-"

[books.one-more-year]
title = "One More Year"
author = ["Megan Praz", "Meghan Kemp-Gee", "Allison Hu", "Richard Mercado"]
format = "graphic"
genres = ["fiction"]
finished = 2024-04-02
media = "paper"
via = "own"
grade = "A-"

[books.heavens-river]
title = "Heaven's River"
author = ["Dennis E. Taylor"]
format = "text"
genres = ["science fiction"]
finished = 2024-04-03
media = "ebook"
via = "own"
grade = "A-"

[books.starter-villian]
title = "Starter Villian"
author = "John Scalzi"
format = "text"
genres = ["science fiction"]
finished = 2024-04-08
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-house-at-seas-end]
title = "The House at Sea's End"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-04-11
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-sun]
title = "The Sun"
author = "Ryan French"
format = "text"
genres = ["non-fiction"]
finished = 2024-04-15
media = "paper"
via = "own"
grade = "A-"

[books.a-room-full-of-bones]
title = "A Room Full of Bones"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-04-15
media = "ebook"
via = "Libby"
grade = "A-"

[books.translation-state]
title = "Translation State"
author = "Ann Leckie"
format = "text"
genres = ["science fiction"]
finished = 2024-04-30
media = "ebook"
via = "Libby"
grade = "A-"

[books.a-dying-fall]
title = "A Dying Fall"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-05-10
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-dog-sitter-detective]
title = "The Dog Sitter Detective"
author = "Antony Johnston"
format = "text"
genres = ["mystery"]
finished = 2024-05-18
media = "ebook"
via = "own"
grade = "A-"

[books.american-eclipse]
title = "American Eclipse"
author = "David Baron"
format = "text"
genres = ["non-fiction"]
finished = 2024-05-24
media = "ebook"
via = "Libby"
grade = "B"

[books.death-and-glory]
title = "Death and Glory"
author = ["Will Thomas"]
format = "text"
genres = ["mystery"]
finished = 2024-05-30
media = "ebook"
via = "Libby"
grade = "A-"

[books.on-work]
title = "On Work"
author = "Derek Thompson"
format = "text"
genres = ["non-fiction"]
finished = 2024-06-02
media = "paper"
via = "own"
grade = "A-"

[books.the-outcast-dead]
title = "The Outcast Dead"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-06-03
media = "ebook"
via = "Libby"
grade = "A-"

[books.sea-of-tranquility]
title = "Sea of Tranquility"
author = "Emily St. John Mandel"
format = "text"
genres = ["science fiction"]
finished = 2024-06-05
media = "ebook"
via = "Libby"
grade = "A"

[books.the-ghost-fields]
title = "The Ghost Fields"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-06-11
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-woman-in-blue-a-mystery]
title = "The Woman in Blue: A Mystery"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-06-18
media = "ebook"
via = "Libby"
grade = "A-"

[books.math-for-programming]
title = "Math for Programming"
author = "Ronald T. Kneusel"
format = "text"
genres = ["non-fiction"]
finished = 2024-06-27
media = "ebook"
via = "author"
grade = "A-"

[books.blood-in-the-machine]
title = "Blood in the Machine"
author = "Brian Merchant"
format = "text"
genres = ["non-fiction"]
finished = 2024-07-06
media = "ebook"
via = "Libby"
grade = "B+"

[books.democracy-or-else]
title = "Democracy or Else"
author = ["Jon Favreau", "Jon Lovett", "Tommy Vietor"]
format = "text"
genres = ["non-fiction"]
finished = 2024-07-08
media = "paper"
via = "own"
grade = "C+"

[books.the-ministry-of-time]
title = "The Ministry of Time"
author = "Kaliane Bradley"
format = "text"
genres = ["science fiction"]
finished = 2024-07-14
media = "ebook"
via = "Libby"
grade = "A"

[books.the-chalk-pit]
title = "The Chalk Pit"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-07-25
media = "ebook"
via = "Libby"
grade = "A-"

[books.the-last-tree]
title = "The Last Tree: A Seed of Hope"
author = "Luke Adam Hawker"
format = "graphic"
genres = ["fiction"]
finished = 2024-07-25
media = "paper"
via = "own"
grade = "A+"

[books.the-hard-switch]
title = "The Hard Switch"
author = "Owen D. Pomery"
format = "graphic"
genres = ["fiction"]
finished = 2024-07-27
media = "paper"
via = "own"
grade = "B+"

[books.together]
title = "Together"
author = "Luke Adam Hawker"
format = "graphic"
genres = ["fiction"]
finished = 2024-08-01
media = "paper"
via = "own"
grade = "A+"

[books.the-dark-angel]
title = "The Dark Angel"
author = "Elly Griffiths"
format = "text"
genres = ["mystery"]
finished = 2024-08-06
media = "ebook"
via = "Libby"
grade = "A-"

[books.king-solomons-mines]
title = "King Solomon's Mines"
author = "H. Rider Haggard"
format = "text"
genres = ["fiction"]
finished = 2024-08-15
media = "paper"
via = "Boulder Public Library"
grade = "C+"

[books.the-peacock-and-the-sparrow]
title = "The Peacock and the Sparrowl"
author = "I.S. Berry"
format = "text"
genres = ["spy"]
finished = 2024-08-19
media = "ebook"
via = "Libby"
grade = "A"

[books.service-model]
title = "Service Model"
author = "Adrian Tchaikovsky"
format = "text"
genres = ["science fiction"]
finished = 2024-08-29
media = "ebook"
via = "Libby"
grade = "A"

[books.play-on]
title = "Play On"
author = "Jeff Bercovici"
format = "text"
genres = ["non-fiction"]
finished = 2024-08-30
media = "paper"
via = "own"
grade = "B"

[books.the-captain-class]
title = "The Captain Class"
author = "Sam Walker"
format = "text"
genres = ["non-fiction"]
finished = 2024-09-07
media = "paper"
via = "own"
grade = "A"

[books.au-japon]
title = "Au Japon!"
author = "Albert Kiefer"
format = "graphic"
genres = ["non-fiction"]
finished = 2024-09-12
media = "paper"
via = "own"
grade = "A"


[books.saevus-corax-deals-with-the-dead]
title = "Saevus Corax Deals with the Dead"
author = "K. J. Parker"
format = "text"
genres = ["fantasy"]
finished = 2024-09-14
media = "ebook"
via = "Libby"
grade = "A-"

[books.atomic-habits]
title = "Atomic Habits"
author = "James Clear"
format = "text"
genres = ["non-fiction"]
finished = 2024-09-19
media = "paper"
via = "own"
grade = "A"

[books.norse-mythology]
title = "Norse Mythology"
author = "Neil Gaiman"
format = "text"
genres = ["non-fiction"]
finished = 2024-09-21
media = "paper"
via = "own"
grade = "B+"
