[books.anthropica]
title = "Anthropica"
author = "David Hollander"
format = "text"
genres = ["fiction"]
finished = 2023-01-01
media = "paper"
via = "own"
grade = "B"

[books.sixteen-ways-to-defend-a-walled-city]
title = "Sixteen Ways to Defend a Walled City"
author = "K. J. Parker"
format = "text"
genres = ["fantasy"]
finished = 2023-01-09
media = "paper"
via = "Boulder Public Library"
grade = "A"

[books.the-echo-maker]
title = "The Echo Maker"
author = "Richard Powers"
format = "text"
genres = ["mystery"]
finished = 2023-01-19
media = "ebook"
via = "Libby"
grade = "A-"