[books.in-cold-blood]
title = "In Cold Blood"
author = "Truman Capote"
format = "text"
genres = ["true crime"]
finished = 2022-01-06
media = "ebook"
via = "Libby"
grade = "A-"

[books.bloodsucking-fiends]
title = "Bloodsucking Fiends"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-01-09
media = "ebook"
via = "Axis 360"
grade = "B+"

[books.seeing-with-fresh-eyes]
title = "Seeing With Fresh Eyes: Meaning - Space - Data - Truth"
author = "Edward Tufte"
format = "text"
genres = ["nonfiction"]
finished = 2022-01-16
media = "paper"
via = "own"
grade = "B"

[books.constant-gardener]
title = "The Constant Gardener"
author = "John Le Carré"
format = "text"
genres = ["suspense"]
finished = 2022-01-19
media = "paper"
via = "Little Library"
grade = "B+"

[books.you-suck]
title = "You Suck"
author = "Christopher Moore"
format = "text"
genres = ["fiction"]
finished = 2022-01-25
media = "ebook"
via = "Axis 360"
grade = "B+"
